name: ami-build

on:
  push:
    branches: 
      - main

jobs:
  build:
    name: ami_build

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configuration
        run: |
            touch .env
            echo PORT=${{ secrets.PORT }} >> .env
            echo DATABASE=${{ secrets.DATABASE }} >> .env
            echo HOST=${{ secrets.HOST }} >> .env
            echo DIALECT=${{ secrets.DIALECT }} >> .env
            echo USER=${{ secrets.USER }} >> .env
            echo PASSWORD=${{ secrets.PASSWORD }} >> .env

      - name: packer variable
        run: |
              cd packer/
              touch variables.pkr.hcl
              echo SOURCE_AMI=\"${{ vars.USER }}\" >> variables.pkrvars.hcl
              echo DATABASE=\"${{ vars.DATABASE }}\" >> variables.pkrvars.hcl
              echo PASSWORD=\"${{ vars.PASSWORD }}\" >> variables.pkrvars.hcl
              echo "Print packer variable file"
              cat variables.pkr.hcl

      # - name: Install packer
      #   run: 
      #    wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
      #    unzip packer_1.7.4_linux_amd64.zip
      #    chmod +x packer
      #    sudo mv packer /usr/local/bin/
      #    packer --version

      - name: Build zip
        working-directory: ${{ github.workspace }}
        run: zip -r webapp1.zip .
             

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Run packer
        run: | 
              cd packer/
              packer init .
              packer fmt .
              packer validate .
              packer build --var-file=variables.pkr.hcl aws-debian.pkr.hcl



        
