name: ami-build

on:
  push:
    branches: 
      - main

jobs:
  build:
    name: ami_build

    runs-on: ubuntu-latest

    env:
      DATABASE: ${{ secrets.DATABASE }}
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      HOST: ${{ secrets.HOST }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configuration
        run: |
            touch .env
            echo PORT=${{ secrets.PORT }} >> .env
            echo DATABASE=${{ secrets.DATABASE }} >> .env
            echo HOST=${{ secrets.HOST }} >> .env
            echo DIALECT=${{ secrets.DIALECT }} >> .env
            echo USER=${{ secrets.USER }} >> .env
            echo PASSWORD=${{ secrets.PASSWORD }} >> .env
            echo aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
            echo aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
            echo aws_region=${{ secrets.AWS_REGION }} >> .env

      - name: Build zip
        working-directory: ${{ github.workspace }}
        run: zip -r webapp1.zip .
             

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Run packer
        run: | 
              cd packer/
              packer init aws-debian.pkr.hcl
              packer fmt aws-debian.pkr.hcl
              packer validate -var-file="variables.pkrvars.hcl" aws-debian.pkr.hcl
              packer build -var-file="variables.pkrvars.hcl" aws-debian.pkr.hcl
  



        
