name: ami-build

on:
  push:
    branches: 
      - main

jobs:
  build:
    name: ami_build

    runs-on: ubuntu-latest

    env:
      DATABASE: ${{ secrets.DATABASE }}
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      HOST: ${{ secrets.HOST }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Build zip
        working-directory: ${{ github.workspace }}
        run: zip -r webapp1.zip .
             

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Run packer
        run: | 
              cd packer/
              packer init .
              packer fmt .
              packer validate .
              packer build \
              -var "USER=${{ env.USER }}" \
              -var "DATABASE=${{ env.DATABASE }}" \
              -var "PASSWORD=${{ env.PASSWORD }}" \
              -var "HOST=${{ env.HOST }}" \
              aws-debian.pkr.hcl
  



        
