name: CI for Application

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: nehajoisher
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: dev_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Wait for PostgreSQL
        run: |
          # Install wait-for-it script
          apt-get update && apt-get install -y wait-for-it
          
          # Wait for PostgreSQL to be ready
          wait-for-it -t 60 localhost:5432 -- echo "PostgreSQL is ready"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: nehajoisher
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: dev_db