name: webapp-CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: webapp-ci

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: 'nehajoisher'
          POSTGRES_PASSWORD: ''
          POSTGRES_DB: ''

        ports:
          - 5432:5432

    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Installing nodemon
        run: npm install nodemon

      - name: Wait for PostgreSQL
        run: |
          apt-get update && apt-get install -y postgresql-client
          until pg_isready -h localhost -p 5432 -U nehajoisher; do
            echo "Waiting for PostgreSQL to start..."
            sleep 1
          done

      - name: Run Jest Tests
        run: npm test