name: Packer Template Validation

on:
  pull_request:

jobs:
  packer_validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build zip
        working-directory: ${{ github.workspace }}
        run: zip -r webapp1.zip .

      - name: Current directory
        run: pwd
             

      - name: configuration
        run: |
            touch .env
            echo port=${{ secrets.PORT }} >> .env
            echo database=${{ secrets.DATABASE }} >> .env
            echo host=${{ secrets.HOST }} >> .env
            echo dialect=${{ secrets.DIALECT }} >> .env
            echo user=${{ secrets.USER }} >> .env
            echo password=${{ secrets.PASSWORD }} >> .env

      - name: Packer fmt
        run: |
          pwd
          cd packer/
          packer init aws-debian.pkr.hcl
          packer fmt -check aws-debian.pkr.hcl
          if [ $? -ne 0 ]; then
            echo "Packer template formatting check failed."
            exit 1
          fi

      - name: Packer validate
        run: |
          pwd
          cd packer/
          packer validate -var-file="variables.pkrvars.hcl" aws-debian.pkr.hcl
          if [ $? -ne 0 ]; then
            echo "Packer template validation failed."
            exit 1 
          fi
